# Generated by Django 4.2 on 2024-08-27 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
